---

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `username` variable needs to be provided to this playbook, via --extra-vars"
  when: "username is not defined or username == '<username>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `email` variable needs to be provided to this playbook, via --extra-vars"
  when: "email is not defined or email == '<email>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `password` variable needs to be provided to this playbook, via --extra-vars"
  when: "password is not defined or password == '<password>'"

- name: Ensure GoToSocial is started
  ansible.builtin.service:
    name: "{{ gotosocial_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the GoToSocial instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Create user account
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} exec {{ gotosocial_identifier }}  /gotosocial/gotosocial admin account create --username {{ username | quote }} --email {{ email | quote }} --password {{ password | quote }}"
  register: gotosocial_create_account_result
  failed_when:
    - gotosocial_create_account_result.rc > 0
    - '"is already in use" not in gotosocial_create_account_result.stderr'
