---

- name: Ensure gotosocial network is created in Docker
  community.docker.docker_network:
    name: "{{ gotosocial_container_network }}"
    driver: bridge


- name: Ensure gotosocial path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ gotosocial_uid }}"
    group: "{{ gotosocial_gid }}"
  with_items:
    - {path: "{{ gotosocial_base_path }}", when: true}
    - {path: "{{ gotosocial_config_path }}", when: true}

- name: Ensure gotosocial data path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ gotosocial_uid }}"
    group: "{{ gotosocial_gid }}"
  with_items:
    - {path: "{{ gotosocial_data_path }}", when: true}


- name: Ensure gotosocial traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ gotosocial_config_path }}/labels"
    owner: "{{ gotosocial_uid }}"
    group: "{{ gotosocial_gid }}"
    mode: 0640

- name: Ensure gotosocial configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ gotosocial_config_path }}/env"
    owner: "{{ gotosocial_uid }}"
    group: "{{ gotosocial_gid }}"
    mode: 0640

- name: Ensure gotosocial image is pulled
  community.docker.docker_image:
    name: "{{ gotosocial_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
  when: "not gotosocial_container_image_self_build | bool"

- name: Ensure gotosocial repository is present on self-build
  ansible.builtin.git:
    repo: "{{ gotosocial_container_repo }}"
    version: "{{ gotosocial_container_repo_version }}"
    dest: "{{ gotosocial_container_src_files_path }}"
    force: "yes"
  register: gotosocial_git_pull_results
  when: "gotosocial_container_image_self_build | bool"

- name: Ensure gotosocial image is built
  community.docker.docker_image:
    name: "{{ gotosocial_container_image_name }}"
    source: build
    force_source: "{{ gotosocial_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mailer_git_pull_results.changed }}"
    build:
      args:
        build-arg: "BUILDPLATFORM=linux/amd64"
      dockerfile: Dockerfile
      path: "{{ gotosocial_container_src_files_path }}"
      pull: true
  environment:
    BUILDPLATFORM: "{{ mash_playbook_architecture }}"
  when: "gotosocial_container_image_self_build | bool"


- name: Ensure gotosocial.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/gotosocial.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ gotosocial_identifier }}.service"
    mode: 0644
